name: Build, Test, Version & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for GitVersion to correctly calculate versions

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1
        with:
          versionSpec: '5.x'

      - name: Determine Version (GitVersion)
        uses: gittools/actions/gitversion/execute@v1
        id: gitversion

      - name: Display Calculated Version
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "NuGet Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Run tests (with Testcontainers)
        run: dotnet test --configuration Release --no-build

      - name: Pack NuGet Package
        if: github.ref == 'refs/heads/main'
        run: dotnet pack --configuration Release --output ./nupkgs /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} --no-build

      - name: Publish to NuGet
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet nuget push ./nupkgs/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      - name: Tag the commit
      - name: Tag the commit
        uses: butlerlogic/action-autotag@1.1.4
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ steps.gitversion.outputs.nuGetVersionV2 }}"
